// schedule.js -- Taught schedule (teacher creates one per class)
// Format: flat enabledProblemTypes list. Teacher ticks what they've taught.
// ENCODING: This file MUST be pure ASCII. All non-ASCII chars are \uXXXX escaped.
// Generated by Schedule Builder on 2026-02-14

// Teacher-only password. Entered on the access code screen to open the cost dashboard.
// Keep this private -- do not share with students.
var TEACHER_DASHBOARD_PASSWORD = "MrMorris2026";

const TAUGHT_SCHEDULE = {
  "className": "12 Methods 2026",
  "teacherName": "Mr Morris",
  "markEndpoint": "https://australia-southeast1-wace-trainer.cloudfunctions.net/mark",
  "sympyEndpoint": "https://australia-southeast1-wace-trainer.cloudfunctions.net/verify",
  "enabledProblemTypes": [
    "Determining decay constant k from given half-life using logarithms",
    "Solving exponential equation $Ae^{kt}$ = target",
    "Finding rate of change by differentiating $Ae^{kt}$",
    "Evaluating exponential model $Ae^{kt}$ at specific time",
    "Solving exponential decay model with percentage rate change to meet threshold condition",
    "Determining parameters of exponential model from two data points",
    "Solving for parameter in exponential model with accumulation to meet target condition",
    "Interpreting long-term behavior of rate of change in exponential model",
    "Determining parameter from initial condition in exponential rational model",
    "Calculating change using exponential model",
    "Finding half-life by solving $Ae^{kt}$ = $A/2$ using logarithms",
    "Solving exponential equation with accumulation model B = A/(1-$e^{-kT}$)",
    "Exponential model problem",
    "Finding tangent point by solving $f'(x) = m$ and using point-slope form",
    "Determining constant in tangent line equation from point on line",
    "Finding x-intercepts of exponential function by factorizing and solving",
    "Exponential function problem",
    "Sketching exponential function with tangent line",
    "Differentiating $x^n \\cdot \\ln(f(x))$ using product rule",
    "Differentiating $x^n \\cdot e^{f(x)}$ using product rule",
    "Differentiating product of polynomial and trigonometric function using product rule",
    "Differentiating $x \\cdot e^{x^2}$ using product rule with chain rule",
    "Evaluating derivative of product using product rule with graph values",
    "Differentiating product of exponential and trigonometric function using product rule",
    "Product rule differentiation",
    "Showing derivative of quotient with exponential denominator using quotient rule",
    "Proving trigonometric derivative identity using quotient rule (show that)",
    "Evaluating derivative of quotient using quotient rule with table values",
    "Differentiating exponential/trigonometric quotient using quotient rule and evaluating",
    "Differentiating exponential rational function using quotient rule to find maximum",
    "Differentiating polynomial rational function using quotient rule",
    "Differentiating a trigonometric quotient using quotient rule",
    "Quotient rule differentiation",
    "Differentiating polynomial composite function using chain rule",
    "Evaluating derivative of composition using chain rule with graph values",
    "Showing derivative of composite function using chain rule and prior result (hence show that)",
    "Chain rule differentiation",
    "Differentiating square root of linear function",
    "Differentiating composite function with square root and trigonometric function",
    "Finding rate of change by differentiation",
    "Differentiation problem",
    "Reading derivative from graph at a point"
  ]
};
